spring.application.name: core-api
spring.profiles.active: local

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - db-core.yml
  mvc.throw-exception-if-no-handler-found: true
#  web.resources.add-mappings: false
  data:
    redis:
      host: localhost
      port: 6379

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

oauth2:
  google:
    client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
    redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI}
    authorization-uri: https://accounts.google.com/o/oauth2/auth
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  admin:
    sub-id: ${OAUTH2_ADMIN_SUB_ID}
    email: ${OAUTH2_ADMIN_EMAIL}
  user:
    sub-id: ${OAUTH2_USER_SUB_ID}
    email: ${OAUTH2_USER_EMAIL}

token:
  secret:
    key: ${TOKEN_SECRET_KEY}
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live

