name: Favorite18-BE-Build

on:
  push:
    branches: ["dev", "main"]

permissions:
  contents: read

jobs:
  build:
    name: Favorite18-BE-CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy Jar File
        uses: appleboy/scp-action
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          timeout: 60s
          source: "core/core-api/build/libs/favorite18-be-app.jar"
          target: "/root/favorite-18/app/be"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          timeout: 60s
          script: |
            cd /root/favorite-18/app/be
            sh ./favorite-18-server-run.sh