name: Favorite18-BE-Build

on:
  pull_request:
    branches: ["dev", "main"]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Favorite18-BE-CI-Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle Build여부로 판단한다. Test가 같이 실행되기 때문에..
      - name: Build with Gradle
        run: ./gradlew build

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle